require "baidu/sem/enum"
require "baidu/sem/base"
require "baidu/sem/report"
require "baidu/sem/account"
require "baidu/sem/adgroup"
require "baidu/sem/bulk"
require "baidu/sem/campaign"
require "baidu/sem/creative"
require "baidu/sem/kr"
require "baidu/sem/keyword"
require "baidu/sem/new_creative"
require "baidu/sem/search"
# require "baidu/ext"
require "savon"